INSERT INTO Producto VALUES('Remera manga larga', 'Roja', 250)
INSERT INTO Producto VALUES('Camisa', 'Blanca', 550)
INSERT INTO Producto VALUES('Swetter rayado', 'negro/blanco', 450)
INSERT INTO Producto VALUES('Pantalon deportivo', 'Negro', 150)
INSERT INTO Producto VALUES('Short baño', 'Varios colores', 350)