--FUNCION SUM SUMA LOS CAMPOS SIEMPRE Y CUANDO SEAN NUMERICOS
SELECT SUM(IDPACIENTE) FROM Pacientes 

--FUNCION SUM CON GROUP BY SUMA LOS AGRUPADOS
SELECT SUM(IDPACIENTE),apellido FROM Pacientes GROUP BY apellido

SELECT* FROM Pacientes